TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../src/tt_um_JorgeArias8644.v ../src/alu_8bit.v ../src/alu_1bit.v ../src/mux2.v ../src/mux4.v ../src/xor3a1n.v
TOPLEVEL = tt_um_JorgeArias8644
MODULE = test_user_module

include $(shell cocotb-config --makefiles)/Makefile.sim
